<?php

declare(strict_types=1);

namespace Iamolayemi\Password0\Exception;

use Throwable;

/**
 * Represents all errors generated by SDK itself.
 *
 * @codeCoverageIgnore
 */
interface BaseException extends Throwable
{
}
