name: Static Anaylsis

on: [ push, pull_request ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    name: php-cs-fixer
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:

          php-version: '8.0'
          tools: composer:v2
          coverage: none

      - name: Install PHP dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run PHP-CS-Fixer
        run: PHP_CS_FIXER_IGNORE_ENV=true vendor/bin/php-cs-fixer fix -v --allow-risky=yes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling

  phpstan:
    runs-on: ubuntu-latest
    name: phpstan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
          coverage: none

      - name: Install PHP dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse  --error-format=github
